# Generated by cpp11: do not edit by hand

add3 <- function(x, y, z) {
  .Call("_tipitaka_add3", x, y, z, PACKAGE = "tipitaka")
}

c_pali_alphabet <- function() {
  .Call("_tipitaka_c_pali_alphabet", PACKAGE = "tipitaka")
}

c_echo <- function(s) {
  .Call("_tipitaka_c_echo", s, PACKAGE = "tipitaka")
}

s_echo <- function(s) {
  .Call("_tipitaka_s_echo", s, PACKAGE = "tipitaka")
}
